### ISSUE TITLE
Differentiate between maintainer, (sales) contact, and maybe external contact

### ISSUE THREAD

**Issue by grtjn** [marklogic/demo-cat#100]
You can currently list only one maintainer. It is not clear whether that person is the contact for technical troubleshooting, information about the demo itself and/or how to run it, or (if running externally) a mediator for reaching out to the company running the demo.

I vote for extra/different fields. Maybe fields like:

- owner
- contact (flagged with external checkbox if non-marklogic)
- troubleshoot (only if non-vanguard?)

Next to this, doesn't sound necessary to list Vanguard as maintainer. I guess people kind of expect Vanguard to know about the demo. Maybe a checkbox to indicate not-managed by Vanguard, when running on a VM out of reach of Vanguard..

**Comment by mariannemyers** [comment]
I'll go with three fields, each which can have one or more people listed (see issue #88)

Business Owner
External Contact
Technical Contact

Currently we have one Maintainer per demo.  For the purposes of data migration, I'd like to move the Maintainer to the Technical Contact field.  The current Maintainer tends to be technical with our current dataset.  Any objections to this migration path?

**Comment by grtjn** [comment]
Sounds good to me. We also discussed adding vertical as property. Where Domain is about target audience is this the departement within ML, who initiated the demo..


Sent from Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Marianne Myers <notifications@github.com> 
Datum: 15-01-2015  17:23  (GMT+01:00) 
Aan: marklogic/demo-cat <demo-cat@noreply.github.com> 
Cc: Geert <geert.josten@xs4all.nl> 
Onderwerp: Re: [demo-cat] Differentiate between maintainer, (sales) contact, and maybe external contact (#100) 
 
I'll go with three fields, each which can have one or more people listed (see issue #88)

Business Owner
External Contact
Technical Contact

Currently we have one Maintainer per demo. For the purposes of data migration, I'd like to move the Maintainer to the Technical Contact field. The current Maintainer tends to be technical with our current dataset. Any objections to this migration path?

**Comment by mariannemyers** [comment]
Should Vertical also support more than one value?

**Comment by grtjn** [comment]
Will be used rately, but yes. Now easy to do..


Sent from Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Marianne Myers <notifications@github.com> 
Datum: 15-01-2015  19:17  (GMT+01:00) 
Aan: marklogic/demo-cat <demo-cat@noreply.github.com> 
Cc: Geert <geert.josten@xs4all.nl> 
Onderwerp: Re: [demo-cat] Differentiate between maintainer, (sales) contact, and maybe external contact (#100) 
 
Should Vertical also support more than one value?

**Comment by mariannemyers** [comment]
Right now demo-cat emails the current maintainer when a bug or comment is written on the demo.  Who should receive this email going forward?

My suggestion:
Bug - Technical Contact
Comment - Business Owner
