### ISSUE TITLE
Features no longer editable

### ISSUE THREAD

**Issue by grtjn** [marklogic/demo-cat#109]
The latest switch from inline edits to create form caused features (and potentially other fields) to no longer be editable..

**Comment by paxtonhare** [comment]
which features are no longer editable?

**Comment by grtjn** [comment]
The 'Features'.. :-)


Sent from Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Paxton Hare <notifications@github.com> 
Datum: 05-01-2015  18:34  (GMT+01:00) 
Aan: marklogic/demo-cat <demo-cat@noreply.github.com> 
Cc: Geert <geert.josten@xs4all.nl> 
Onderwerp: Re: [demo-cat] Features no longer editable (#109) 
 
which features are no longer editable?

**Comment by paxtonhare** [comment]
on the develop branch
