### ISSUE TITLE
Data needed for new UI

### ISSUE THREAD

**Issue by jenbreese** [marklogic/demo-cat#120]
I need assistance getting the following into the new design.
1. A two line description
2. A list of the features
3. The MarkLogic version
4. List of supported browsers
![newdetailbox](https://cloud.githubusercontent.com/assets/1187335/5672642/18d0819e-9747-11e4-8859-11aa5aaacb19.png)

**Comment by jenbreese** [comment]
I would prefer a short description because it can be written purposefully short. The long description might ramble and not get to the point. What if we implement your suggestion? Look for the short one but take the first n characters from the full one as a backup plan.

I will look into the data you mention above. I might need assistance, however.

**Comment by grtjn** [comment]
You might need to use a result decorator, though extract-metadata should get you most of the way. Just let know if you need a hand with anything..

"Help is always given to those who ask for it" - Dumbledore ;-)


Sent from Samsung Mobile

**Comment by jenbreese** [comment]
I removed the idea of browsers.

**Comment by grtjn** [comment]
Fixed in dev
