### ISSUE TITLE
Announcement on landing page

### ISSUE THREAD

**Issue by grtjn** [marklogic/demo-cat#123]
General purpose area in the ui to show a message. Maybe to show off some content, or maybe for work in progress notes..

**Comment by jenbreese** [comment]
I created a branch in my fork called announcements that has the look of the section done. Should the branch be pulled into this project?
Now it needs:
1. a form to fill in to populate
2. populate my flat html

**Comment by grtjn** [comment]
Discussed with Jen the idea of a new home page for announcements. Instead of opening at search results, open a dashboard with announces, 1 or 2 facet value top-5's, potentially a tiny message/news feed (I will demo this then there..), etc..

**Comment by grtjn** [comment]
Fixed in develop, we have vanguard news, don't touch, and spotlight sections.
