### ISSUE TITLE
Allow adding 'memos' to demos

### ISSUE THREAD

**Issue by grtjn** [marklogic/demo-cat#125]
How about allowing creation of custom 'pages' with additional details about the demo? We could use a rich or markdown kind of editor, and store the pages within demo-cat. Allows searching them, and you would depend less on external systems, which is often a bit fragile. Jumping back and forth can also be a bit of a pain between different systems.

One could refer to such 'pages' as 'Memo's'.

**Comment by jenbreese** [comment]
I like the idea. There is a lot of information in the Wiki that could be pulled over into these memos. I think they could be organized as extra pages and links could be added in the left col, instead of making the page really long.

**Comment by grtjn** [comment]
Fixed in develop
