### ISSUE TITLE
Search bar looks odd

### ISSUE THREAD

**Issue by grtjn** [marklogic/demo-cat#140]
Once you enter a search term, the X to remove the search string seems to get misplaced.

**Comment by grtjn** [comment]
I'll send a screenshot offline..

**Comment by jenbreese** [comment]
I wasn't able to reproduce on my local build. I sent screenshots as well.

**Comment by grtjn** [comment]
Strange, could not reproduce locally either, only on server. Redeployed to server, still the same. I'll take a closer look..


Sent from Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Jen Breese <notifications@github.com> 
Datum: 31-01-2015  00:10  (GMT+01:00) 
Aan: marklogic/demo-cat <demo-cat@noreply.github.com> 
Cc: Geert <geert.josten@xs4all.nl> 
Onderwerp: Re: [demo-cat] Search bar looks odd (#140) 
 
I wasn't able to reproduce on my local build. I sent screenshots as well.

**Comment by jenbreese** [comment]
Any luck with recreating this @grtjn?

**Comment by grtjn** [comment]
Not locally. Still need to look closer on the server..


Sent from Samsung Mobile

**Comment by grtjn** [comment]
Found the issue, server was using bootstrap 3.0, and you were using classes from 3.2. Apparently bower install doesn't watch for version changes in bower.json. A bower update fixed the problem, and touching main.less solved the problem..
