### ISSUE TITLE
Wrapping search results at browser resize

### ISSUE THREAD

**Issue by grtjn** [marklogic/demo-cat#141]
With the recent layout changes, 3 tiles are shown next to each other. If you make the browser smaller, they are squeezed, and start to look ugly. If would be nice if the layout would show less tiles next to each other, to keep the tile size the same as much as possible.

We should also change page size to 12, to allow showing a nice grid of 3x4, 2x6 or 1x12..

**Comment by grtjn** [comment]
@jenbreese is this doable?

**Comment by jenbreese** [comment]
@grtjn Yes, it is doable. I'm working on it.

**Comment by grtjn** [comment]
The presentation has improved for mobile, but it is not yet doing it gradually. It is still showing 3 tiles next to each other, unless you make the browser really small. What I had in mind was showing facets, and 3 demos at full width on laptop, show facets and 2 demos at 75%, show facets and 1 demo at 50%, and show facets with demos in single queue below at around 25% of a laptop screen width. Or something along those lines..

Would it make sense to not use grid, but just a fixed width left float for the demo cards? The browser should wrap them around automatically given available width, right?

**Comment by jenbreese** [comment]
@grtjn - I see your point. I moved it so the middle width will have 2 across.  The widths are broken up like this. It would be best if we could get some devices to actually test it. 
/* Panel collapsing: Small devices (tablets, 768px and up) */
/* Panel collapsing:  Medium devices (desktops, 992px and up) */

**Comment by grtjn** [comment]
Should be fixed in develop
