### ISSUE TITLE
Upgrade ml-search for metadata bugfix

### ISSUE THREAD

**Issue by grtjn** [marklogic/demo-cat#143]
We need to upgrade ml-search to benefit from this bug fix:

https://github.com/joemfb/ml-search-ng/issues/15

Does ml-search need to be released first?

**Comment by grtjn** [comment]
@joemfb what needs to happen to get this in demo-cat?

**Comment by joemfb** [comment]
sorry, I left this hanging. I'll push a new point release today

**Comment by joemfb** [comment]
I've pushed a new version of ml-search-ng (v0.0.10). Run `bower update` to get the latest.

**Comment by grtjn** [comment]
Confirmed, bower update did the trick..
