### ISSUE TITLE
Preview of attachments

### ISSUE THREAD

**Issue by grtjn** [marklogic/demo-cat#165]
Clicking an attachment now downloads it. Might be nicer to try to preview it. PDF, image, and video can be previewed very easily using an object tag. Could be opened in a modal like memos, reusable code for that should be in place..

**Comment by ryanjdew** [comment]
Related to #45

**Comment by grtjn** [comment]
Media attachments and media links get mixed up..

**Comment by grtjn** [comment]
Fixed in PR #185

**Comment by grtjn** [comment]
Fixed in develop
