### ISSUE TITLE
Domains not working on create.html

### ISSUE THREAD

**Issue by jenbreese** [marklogic/demo-cat#177]
The domain fields are no longer working in the create.html. They likely don't work on the demo details page as well but I cannot test that.

**Comment by grtjn** [comment]
Domains not showing nor editable in both create and edit. It looks like code behind features and technologies was changed, but domains didn't change along. I think it would be nice if domains would be data driven as well..

**Comment by grtjn** [comment]
Fixed in pending PR #185

**Comment by grtjn** [comment]
Fixed in develop
