### ISSUE TITLE
A usability & documentation suggestion to the git readme.md install instructions 

### ISSUE THREAD

**Issue by sgehringDesign** [marklogic/demo-cat#192]
On the read me instruction you may want to change
```
$ ml local bootstrap
$ ml local deploy modules
```

to

```
$ ./ml local bootstrap
$ ./ml local deploy modules
```
This way newbies and beginners to not have to figure out how to install ml in their path...

**Comment by grtjn** [comment]
+1, I prefer that style too. There could also be important bugfixes in the local ml. When you create a new project, you always get a fresh version..

**Comment by grtjn** [comment]
Oh actually, this is more a Roxy issue. Maybe better to move this over to https://github.com/marklogic/roxy..

**Comment by dmcassel** [comment]
It's something we should address in Roxy documentation as well, but @sgehringDesign is proposing a change to demo-cat's README.

**Comment by grtjn** [comment]
a PR would be welcome! :)

**Comment by jenbreese** [comment]
@grtjn All done. :)

**Comment by grtjn** [comment]
Fixed in master.
