### ISSUE TITLE
Attach or link a demo script

### ISSUE THREAD

**Issue by dmcassel** [marklogic/demo-cat#2]
Add a link to a demo script on create/view/edit a demo.

**Comment by grtjn** [comment]
One could refer to such 'pages' as 'Memo's'. Let me create a separate ticket for it, since it is so different from the link/attachment idea.

**Comment by bluetorch** [comment]
Where would be the ideal place to store the binary files?  On the filesystem for NodeJS to serve, or in the MarkLogic database?

**Comment by dmcassel** [comment]
If they are on the filesystem, you have the option to also record them in MarkLogic as [external files](http://docs.marklogic.com/guide/ingestion/xquery#id_68661). That way, Node could serve them (avoiding the extra trip to MarkLogic), but MarkLogic could still filter them for metadata.

**Comment by grtjn** [comment]
Storing them in ML allows making consistent backups easily. You could cache binaries in node for performance if necessary.

May depend on how often we think those binaries are going to be accessed. And how large/many..

**Comment by grtjn** [comment]
In progress..

**Comment by grtjn** [comment]
Fixed in develop
