### ISSUE TITLE
Can't add comment to a demo instance

### ISSUE THREAD

**Issue by jmakeig** [marklogic/demo-cat#223]
For example, on the [Toppan Forms](https://catalog.demo.marklogic.com/detail/demos/17538482890161490330.json) instance, I tried to add a comment that the "Accessible at" link wasn't working. However, when I press the Add button nothing happens. In the browser console I get, `[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (comment, line 0)` for the link `https://catalog.demo.marklogic.com/v1/resources/comment?rs:uri=%2Fdemos%2F17538482890161490330.json`.

Browser is Safar 8.0.5 (10600.5.17) on OS X 10.10.3 (14D136).

**Comment by grtjn** [comment]
I'll look into this..

**Comment by grtjn** [comment]
Fixed in develop, and pushed to server..
