### ISSUE TITLE
Make Visualizations Widgets facet always appear

### ISSUE THREAD

**Issue by jenbreese** [marklogic/demo-cat#244]
The visualizations facet (feature) should always appear rather then having to click 'More'. 
One solution would be to make sure the demos that have them are including it as a feature. This list is sorted numerically with the most on top.

**Comment by grtjn** [comment]
This should be content driven to my opinion. We only need 1 more demo marked with this feature to get it in the top 5, and a few more to get it to position 2. But, I think we should be careful with what to mark with that feature, as I think people expect we mean:

http://developer.marklogic.com/products/visualization-widgets#&panel1-1

They are built into app-builder whenever you use a chart or map.

**Comment by grtjn** [comment]
We now have a link on the main page that pushes demos with viz widgets. I vote we close this ticket..

**Comment by jenbreese** [comment]
I agree. Closing it.
