### ISSUE TITLE
Homepage and header edits

### ISSUE THREAD

**Issue by jenbreese** [marklogic/demo-cat#249]
1.  I was asked to remove the Services from the homepage and allow the News to fill the container 100%. Will removing the Services from the homepage be enough or do further changes need to happen?
2.  Asked up update the search/magnifying glass to make it more clear it is search button.  Added color to it as well as a link cursor. 

Both have been done and should be reviewed.

**Comment by grtjn** [comment]
I merged the changes to make it easier to review things.

**Comment by grtjn** [comment]
I think it looks good..
