### ISSUE TITLE
Problems with adding links in the News section

### ISSUE THREAD

**Issue by jenbreese** [marklogic/demo-cat#256]
The links aren't working properly to a filtered search. Try the last link in the news section that is currently available. If you click on Next or 2 the pagination box redraws. When you first land on the page, it appears as if it is listing everything.

**Comment by grtjn** [comment]
I'm able to reproduce this. It is caused by the bare search() in search-ctrl.js. That should be triggered by fromParams, so it runs after parsing params, and not before..

**Comment by grtjn** [comment]
Fixed in dev
