### ISSUE TITLE
create initial documents for local development

### ISSUE THREAD

**Issue by patrickmcelwee** [marklogic/demo-cat#261]
The UI depends on '/dont-touch.json', '/vanguard.json', and 'spotlight.json'. This provides those, so a run of `./ml local deploy content` will load them for someone getting started with a new local instance. Also, I provided one spotlighted demo.

We should also consider checking in Dave Cassel's sample data. There are instructions in the README to download them, but I don't see much downside to simply checking them in.

**Comment by grtjn** [comment]
The PR adds real data, they should provide empty files, and we need to put those files outside data/ in case we need to deploy an update for quick-filters.json or such. We can't risk wiping the good files from production. To my knowledge the UI will create new files itself as soon as you start editing, but I could be wrong..

**Comment by grtjn** [comment]
I reverted the changes, and pruned the history. Those files should not be in the repository..
