### ISSUE TITLE
Error submitting comment

### ISSUE THREAD

**Issue by dmcassel** [marklogic/demo-cat#278]
I tried to submit a comment on a demo detail page. I got this error visible in the browser console:

> {"errorResponse":{"statusCode":500, "status":"Internal Server Error", "messageCode":"INTERNAL ERROR", "message":"XDMP-AS: (err:XPTY0004) let $recipient-names as xs:string := for $recipient in $recipients return ($recipient/jbasic:name, \"Vanguard\")[1] -- Invalid coercion: (\"Vanguard\", \"Vanguard\") as xs:string . See the MarkLogic server error log for further detail."}}

For debugging:

request payload: 

> {"msg":"Is this multi-tenant?","id":null,"username":null,"dateTime":null}

Browser: Chrome Version 55.0.2883.95 (64-bit)

From the response: Date:Thu, 09 Feb 2017 15:39:41 GMT

**Comment by grtjn** [comment]
Fixed in dev..

**Comment by grtjn** [comment]
Took a while, but finally deployed to server..
