### ISSUE TITLE
Add a section for demo restrictions

### ISSUE THREAD

**Issue by dmcassel** [marklogic/demo-cat#3]
Some demos are only be shown to certain organizations. Add a place to record those restrictions.

**Comment by grtjn** [comment]
Would be best if restricted demos are shown with some visual distinction in search results. Maybe red border, maybe some nice exclamation mark. Details about restriction in popup (nice), or on details page (must)..

**Comment by jenbreese** [comment]
I will send you the code and a screenshot of what I have in mind for the restricted access.

**Comment by grtjn** [comment]
I guess that comment was meant for @daveegrant, right?

**Comment by jenbreese** [comment]
@grtjn Oops, yes it was.

**Comment by daveegrant** [comment]
Pull request was submitted with updates for this ticket.

**Comment by daveegrant** [comment]
Merged to develop.
