### ISSUE TITLE
Add the ability to specify > 1 maintainer

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/demo-cat#88]
I see us cheating and doing comma separated for Maintainer. Let's just add the ability to do more than one.

**Comment by mariannemyers** [comment]
I'm planning to migrate the Maintainer into the new Technical Contact field as described in #100.  

I've written the XQuery to migrate the data.  Should we simply run it in Query Console prior to or after deployment, or CM it?  It only needs to be run once.

**Comment by paxtonhare** [comment]
I would CM it. Then run how/whenever.
