### ISSUE TITLE
Follow a demo with alerts

### ISSUE THREAD

**Issue by dmcassel** [marklogic/demo-cat#90]
Allow a person to Follow a demo. Following means that any update to the demo (description, features, comments, bug updates, etc) will trigger an email. 

Simple version: send an email immediately. 

Better (maybe a different ticket): an individual can specify how often he/she wants to receive emails: immediate, daily, weekly.

**Comment by mariannemyers** [comment]
I would like to implement this using Alerting, but I need some guidance on the proper rule to create.

I'll add a button to a demo page to “Follow this demo”, and a converse “Unfollow this demo”.  

To store follow information, I plan to change the User data model some.  For example, 
/user/mmyers.json will contain a new array:
```xml
<follows>
	<follow>
		<uri>/demo/uri.json</uri>
	</follow>
<follows>
```
I will have an XQuery module (say send-demo-updated-email.xqy) that sends an email immediately (for now) when the rule is matched.

Question: What is the right rule to build such that the module will be invoked when a document URI that is followed is updated?  This doesn't fit the convenient keyword search based examples I am finding as examples.

**Comment by paxtonhare** [comment]
You can use a cts:document-query() on the uri. I think that's what you are asking.

**Comment by mariannemyers** [comment]
I'd like to add a link back to the demo in Demo Cat in the email that my alert generates.  To solve this we'll add a new property, public-hostname, that can vary based on environment (i.e. public-hostname=catalog.demo.marklogic.com).  We'll need to include this in our appropriate .properties files. 

Any objections to this addition?

**Comment by grtjn** [comment]
Put a sensible default in build.properties, and override it in env specific properties. How did you intend to get that pushed automatically into code? You could put a Roxy placeholder in `src/app/config/config.xqy`, I believe that gets special treatment at deploy modules..

**Comment by grtjn** [comment]
But if I recall correctly some of the notification stuff was already assuming that a Host or Referrer header was being sent through, from which you should be able to derive host dynamically?

**Comment by mariannemyers** [comment]
Thanks @grtjn for helping me see this differently.   Also a shout out to @daveegrant for his assistance.

I'll capture the referring host in <alert:options> when I alert:make-rule. I'll then use that same hostname saved as part of the rule to generate a link back to Demo Cat for the email notification when the Alert is triggered.

**Comment by grtjn** [comment]
We can always opt for props if it turns out not to work well in production for some reason. On the new server it will be going through Apache Httpd converting https to http as well. Headers could get lost in translation easily there..

**Comment by grtjn** [comment]
Should be fixed in develop
