### ISSUE TITLE
Add some feature to record whether the demo is working or not

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/demo-cat#91]
Perhaps the user can click a button that says "Works", "Doesn't Work". Then we could store the status and timestamp as something like "demo-status".

This would allow users a quick way to flag a demo. Helps to keep things fresh. We could then facet on things like show demos that haven't been verified in a long time.

Possible future enhancements would be to alert the demo owner that it isn't working.

could also allow a user to say what isn't working.

**Comment by daveegrant** [comment]
Should we alert the maintainer whenever any field is updated or only when this new <demo-status> is updated?

**Comment by grtjn** [comment]
I'd say a high prio mail when this field changes, a normal prio one for all other changes?

**Comment by daveegrant** [comment]
fix merged into develop branch
